### ISSUE TITLE
frontmatter imports not working for any format supported by a resource plugin 

### ISSUE THREAD

**Issue by lschierer** [ProjectEvergreen/greenwood#1319]
## Type of Change

Feature

## Summary

the imports field in the frontmatter filters out any files that are not .js and not .css,  please support any format supported by any Adapter plugin.  

## Details

I noticed this trying to import a typescript component in a project that has the typescript plugin enabled.  the component works fine if included via layout, and also works fine if included by another component.   If however, I attempt to use the imports field, then the corresponding script tag is not generated and the component does not hydrate, it gets processed as an unknown tag.

**Comment by thescientist13** [comment]
yeah, this seems like probably just an oversight and at a quick glance, probably not specific to TS, just anything not a _.js_ or _.css_ file, but agreed, Greenwood should certainly make sure any resource type supported by a resource plugin also carries support for it in frontmatter imports

**Comment by lschierer** [comment]
I'm looking at the TypeScript source plugin ATM, and I think a generic solution to this would entail the core application, as a new source plugin is registered, adding its "this.extensions" property to some more central global array of acceptable extensions that it filters the files in the front matter imports by.   This is me hypothesizing from what I'm seeing in the code so far at least.

**Comment by thescientist13** [comment]
Yup, pretty much.

Taking a quick look now, custom imports are [processed starting here](https://github.com/ProjectEvergreen/greenwood/blob/master/packages/cli/src/lib/layout-utils.js#L234) in the `getAppLayout` function, where we just filter on extension, so that's where we would want to open up embedding `<link>` and `<script>` tags to more than just _.js_ and _.css_ extensions.  Greenwood does processing like this by pulling all plugins out of [`compilation.config.plugins`](https://greenwoodjs.dev/docs/reference/appendix/#compilation) and checking instances of plugins in the way you describe, e.g. [like this](https://github.com/ProjectEvergreen/greenwood/blob/master/packages/cli/src/config/rollup.config.js#L79), though I think for this case we wouldn't need to actually process these files.  We just need to make sure there is at _a_ plugin to handle it .

I _think_ it might also need to be handled in the [`modelResource` function](https://github.com/ProjectEvergreen/greenwood/blob/master/packages/cli/src/lib/resource-utils.js#L7) as well, which has similar hardcoded check, but not 100 positive, but would probably be the same logic.

(also, just a minor technical point, but the TypeScript plugin is technically a [resource plugin](https://greenwoodjs.dev/docs/reference/plugins-api/#resource))

**Comment by thescientist13** [comment]
Got a PR for this up now, and also found a couple other small bugs / tweaks that will benefit Greenwood overall, be it regular resources or a frontmatter imports.

Thanks again for the report, will get this queued up for an upcoming alpha release in the v0.31.0 line. 👍

**Comment by thescientist13** [comment]
Yeah, the PR for this one hasn't been merged yet, **alpha.0** was just to validate the first round of PNPM and import map changes, so will get this out for **alpha.1** once I've had a chance to digest any compatibility issues with those changes across some of my projects, and to fully complete the work around #1313 / #684 .
