### ISSUE TITLE
filenames that include existing directory name in the filename causes compilation error

### ISSUE THREAD

**Issue by hutchgrant** [ProjectEvergreen/greenwood#132]
## Type of Change
- [ ] New Feature Request
- [ ] Documentation / Website
- [ ] Improvement / Suggestion
- [x] Bug
- [ ] Other (please clarify below)

## Summary
If you name a file `creating-pages.md` in the pages directory, it will throw an error that the file wasn't found.

## Details
I think this error is related to a regex when we're looking for files within the `pages` directory.

edit: Same bug also we cannot use the word `templates` (with an s) within a filename.  It seems `pages` and `templates` are reserved words.

**Comment by thescientist13** [comment]
@hutchgrant 
Can you take a few minutes and refresh on what the issue is, I forget if it is a simple or hard problem to solve?

**Comment by thescientist13** [comment]
opened the PR to document this for now at least

**Comment by thescientist13** [comment]
Was working on #115 and was playing around with `graphql` and wanted to to create a _pages.gql_ file which lead to me getting errors like
```shell
ERROR in ./www/components/header/header.js
Module not found: Error: Can't resolve '/queri/Users/owenbuckley/Workspace/project-evergreen/repos/greenwood/www/pages.gql' in '/Users/owenbuckley/Workspace/project-evergreen/repos/greenwood/www/components/header'
 @ ./www/components/header/header.js 5:0-49 14:17-27
 @ ./.greenwood/index/index.js
 @ ./.greenwood/app/app.js
 @ multi webpack-dev-server/client?http://localhost:1984 ./.greenwood/app/app.js
```


Eventually I remembered this issue so I figured I would take a look into it since I could see this getting more annoying as page creation becomes more dynamic (e.g. #21 ).

So spent a couple hours and I'm pretty sure the entire solution comes to a one character change as after a bunch of trial and error, it dawned on me what would be different between a _file_ called **pages**, and a _directory_ called **pages**.   A `/`, as a file will have an extension, which means _pages.xx_ won't match _pages/_.  🤞 
```javascript
// before
new RegExp(`${directory}`), (resource) => {

// after
new RegExp(`${directory}\/`), (resource) => {
```


Playing around with it looking good.  Will try out a couple more tests and open a PR soon if all looks good.

**Comment by thescientist13** [comment]
Also, I think I was able to narrow down the use case.  Essentially the issue is that if you have
```
www/
  pages/
    about.md
```

And then create something like
```
www/
  pages/
    about.md
  queries/
    pages.gql
```

This will end up having the resource request to pages.sql match against the directory mapping for _pages/_.  

So it's not a set list, but rather what your folders structure is.  Filenames that include a directory name in them will not get mapped to the correct parent directory.
