### ISSUE TITLE
misc website fixes and tweaks

### ISSUE THREAD

**Issue by thescientist13** [ProjectEvergreen/greenwood#157]
## Type of Change
- [ ] New Feature Request
- [ ] Documentation / Website
- [ ] Improvement / Suggestion
- [ ] Bug
- [x] Other (please clarify below)

## Summary
Just an ongoing list of small issues that anyone can pick up and help out with.

## Details
1. [x] On the home page, the logos at the bottom aren't in evenly spaced columns
1. [x] The images like at the bottom of the Getting Started -> Build and Deploy section forces a horizontal scroll bar
1. [x] Remove browser prefixes from CSS files (also delete any unused / unneeded CSS)
1. [x] Upon first load, the logo in the banner "jumps out", looks like a [FOUC](https://en.wikipedia.org/wiki/Flash_of_unstyled_content) maybe?

**Comment by aholtzman** [comment]
I may have solved the above issues (80% sure the homage FOUC is resolved) plus all the spelling fixes Atom pointed out to me on branch website/mics-fixes-and-tweaks_issue157

**Comment by hutchgrant** [comment]
I have the fix for the third item with the banner and header jumping(which seems only apparent in chrome). To see the bug easier, set your browser to slow3g

for the banner: 

* set a max-width and max-height on the banner img

for the header:

* change from the h4 to a custom class, the global style's h4 specificity is higher because it's set to `important` which is messing with the style on load.
