### ISSUE TITLE
404 page not building and serializing correctly

### ISSUE THREAD

**Issue by thescientist13** [ProjectEvergreen/greenwood#176]
## Type of Change
- [ ] New Feature Request
- [ ] Documentation / Website
- [ ] Improvement / Suggestion
- [x] Bug
- [ ] Other (please clarify below)

## Summary
Observed a couple issues with 404 page, the default anyway.  Observed from [my own project](https://github.com/thegreenhouseio/www.thegreenhouse.io/issues/112) but also in getting started companion repo.  Probably exists in _www/_ too.

**develop**
1. `<title>` is default value, _My App_.  Not sure if there could be more missing config items, like `meta` or others?
<img width="310" alt="Screen Shot 2019-08-19 at 5 29 38 PM" src="https://user-images.githubusercontent.com/895923/63300781-09211200-c2a7-11e9-8efb-bae93e65c0af.png">

**build**
1. It doesn't seem to exist at all?
<img width="703" alt="Screen Shot 2019-08-19 at 5 29 33 PM" src="https://user-images.githubusercontent.com/895923/63300768-032b3100-c2a7-11e9-90d5-c780fe0826d7.png">

## Details
Maybe this is more of a need around documentation as well?  Not 100% clear what the expectations are.  Do users make their own 404.md?  

> **Would be better to do this instead > #200**

**Comment by hutchgrant** [comment]
The result you're seeing is because you're running a [`local-web-server`](https://www.npmjs.com/package/local-web-server). Which you'll note from their documentation:

> With a static site, requests for typical SPA paths (e.g. /user/1, /login) would return 404 Not Found as a file at that location does not exist. However, by marking index.html as the SPA you create this rule:
> 
> If a static file is requested (e.g. /css/style.css) then serve it, if not (e.g. /login) then serve the specified SPA and handle the route client-side.
> 

Adding `-spa index.html` to `"serve": "yarn build && cd ./public && ws",
` 
forces it to use the client for routing and thus the hard coded 404 displays:

``` 
<lit-route><h1>404 Not found</h1></lit-route> 
```

When you're hosting on a static host, you aren't using local-web-server and `404.html` is the default file.

By default, the 404.html included is with the package is used. If a 404.html is present in workspace, then that file is the file is copied to the public/404.html path.

You'll note in the webpack.config.prod.js

```
    plugins: [
      new HtmlWebpackPlugin({
        filename: path.join(context.publicDir, context.notFoundPageTemplate),
        template: path.join(context.scratchDir, context.notFoundPageTemplate),
        publicPath: configWithContext.output.publicPath
      })
    ]
```

Which is using our notFoundPageTemplate, based on the `lifecycles/context`.
```
context =  {
        notFoundPageTemplatePath: userHasWorkspaceNotFoundTemplate
          ? path.join(userTemplatesDir, notFoundPageTemplate)
          : path.join(defaultTemplatesDir, notFoundPageTemplate),
}
```

So as long as your workspace/templates directory contains a 404.html, that will be used instead of the default one.

**Comment by hutchgrant** [comment]
I'm thinking, `404.md` file could be injected into the app-template.js and we could serialize it to 404.html

**Comment by thescientist13** [comment]
Maybe we shouldn't have a 404 page at all?  I'd rather lean towards that, or maybe a plugin could be made for it instead if that's valuable.

**Comment by thescientist13** [comment]
let's defer to #200 instead

**Comment by thescientist13** [comment]
not really a bug, but rather just a feature that just needs proper discussion / documentation / building and so will do that as part of #240 instead.
