### ISSUE TITLE
should .greenwood directory be cleared out on each build

### ISSUE THREAD

**Issue by thescientist13** [ProjectEvergreen/greenwood#230]
## Type of Change
- [ ] New Feature Request
- [ ] Documentation / Website
- [ ] Improvement / Suggestion
- [ ] Bug
- [x] Other (please clarify below)

## Summary
Just posing this as question coming out of our work in #213 
https://github.com/ProjectEvergreen/greenwood/pull/217#issuecomment-541325788

## Details
In this comment, was curious if wiping .greenwood/ was something we should do between builds?  I know down the road this may not be desirable if we want to do any sort of local caching of remote data sources like with #21 , but maybe we could isolate that to _.greenwood/cache/_

**Comment by hutchgrant** [comment]
It's problematic because if you add/remove a page/route the `app/app.js` and `app/list.js` must be rebuilt/parsed.  I suppose we could just wipe the `.greenwood/app` directory alone on change.

Also if any of the front-matter details change in a markdown file E.g. meta, or labelling, etc, we have to rebuild the component.  Sure you could remove the previous component file, if it exists, then rewrite the file, and then reserialize.  

Speaking serializing, ours does every page, every time, to just serialize specific pages, modifications would have to be made as well.  

There's room for optimizing but its a lot of effort and shouldn't be the immediate focus. What good is a speedier compile if the build itself is limited in features.

Therefore it's easier, for now, if there's any changes to wipe the directory. This can change in the future.

**Comment by thescientist13** [comment]
It seems like this is already happening, so nothing to do here.  :)
