### ISSUE TITLE
refactor navigation and shelf into single query

### ISSUE THREAD

**Issue by hutchgrant** [ProjectEvergreen/greenwood#291]
## Type of Change
- [x] New Feature Request
- [ ] Documentation / Website
- [x] Improvement / Suggestion
- [ ] Bug
- [ ] Other (please clarify below)

## Summary

As per #285, I would like to suggest we refactor navigation and shelf into a single Menu query through graphql as described [here](https://github.com/ProjectEvergreen/greenwood/issues/271#issuecomment-582704831)

## Details

schema
```
  type Link {
    label: String,
    link: String
  }

  type Menu {
    item: Link
    children: [Menu]
  }

  enum MenuOrderBy {
    label_asc,
    label_desc
    index_asc,
    index_desc
  }

  type Query {
    menu(filter: String, orderBy: MenuOrderBy): Menu
  }

```

our query from our components(both header and shelf):

```
query($menu: String!,  $order: String) {
  menu(filter: $menu, orderBy: $order) {
    item {
      label,
      link
    }
    children {
      item {
        label,
        link
      },
      children {
        item {
          label,
          link
        }
      }
    }
  }
}
```

This will work for both navigation, side menus, footers, etc.  We can filter by menu type and sort the menus as well.

**Comment by thescientist13** [comment]
Yeah, this could make a lot of sense, since really the only difference between Navigation and Children queries is that Navigation is just "capped" at a depth of 1.  Same could be achieved through one query as you suggest.

I think this would solve part of #273.  Not everywhere I don't think since there are various usages of `[0]` but certainly for queries it would.
