### ISSUE TITLE
remove "magic" strings MDIMPORT / MYROUTES

### ISSUE THREAD

**Issue by thescientist13** [ProjectEvergreen/greenwood#322]
## Type of Change
- [ ] New Feature Request
- [ ] Documentation / Website
- [x] Improvement / Suggestion
- [ ] Bug
- [ ] Other (please clarify below)

## Summary
Currently a page template needs at least a `MDIMPORT` "magic" string that gets templated at build time by the Greenwood CLI.  It would be ideal if this could be removed entirely.

This carries on work done as part of #125 where we were able to remove `METAIMPORT`, `METADATA`,  and `METAELEMENT`.

We also need to try and do the same for [`MYROUTES`](https://github.com/ProjectEvergreen/greenwood/pull/265#discussion_r418377589)

**Comment by hutchgrant** [comment]
You could have the scaffold.js read the template file and then write the string at top or after all the imports to satisfy the `mdimport` problem.  You could do something similar with the other magic strings.  I don't recommend doing that with `myroutes` because as with 

```
const templateData = await fs.readFile(pageTemplatePath, 'utf8');

let result = templateData.toString().replace(/entry/g, `wc-md-${file.label}`);
result = result.replace(/MDIMPORT;/, `import '${file.mdFile}';`);
```

If we use that method we have to read line by line of the app/page-templates and we have to do this for every single page. Far less efficient than simply using the current method. But yea, cleaner for the developer just wanting to write a template file in their project.

But just like the `<entry></entry>` element, the `MYROUTES` element is needed for specific placement the author wants. You can't eliminate those unless you want to eliminate giving them the choice to play routes/md files however they want in their templates. It's a fundamental function.
